export const GET_ALL_APPOINTMENTS = 'GET_ALL_APPOINTMENTS';
export const ADD_NEW_APPOINTMENT = 'ADD_NEW_APPOINTMENT';
export const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT'
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT'
